[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-mios-version-min=13.0"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-arg=-mios-version-min=13.0"]

[target.x86_64-apple-ios]
rustflags = ["-C", "link-arg=-mios-version-min=13.0"]

[env]
IPHONEOS_DEPLOYMENT_TARGET = "13.0"
